import java_cup.runtime.*;
import java.util.*;

terminal NEWLINE, PIPE, SEMI, REDIR, APPEND;
terminal String IDENT;

non terminal Object line;
non terminal Object cmd_list;
non terminal Object command;
non terminal List<String> args;
non terminal RedirectInfo redir;

start with line;

line ::=
      cmd_list NEWLINE
    | NEWLINE
    ;

cmd_list ::=
      command
    | cmd_list SEMI command
    ;

command ::=
        IDENT:cmd args:a redir:r
          {:
              CommandExecutor.execute(cmd, a, r);
              RESULT = null;
          :}
    ;

args ::=
        {:
            RESULT = new ArrayList<String>();
        :}
    | args:a IDENT:i
        {:
            a.add(i);
            RESULT = a;
        :}
    ;
redir ::=
        {:
            RESULT = null;
        :}
    | REDIR IDENT:file
        {:
            RESULT = new RedirectInfo(file, false);
        :}
    | APPEND IDENT:file
        {:
            RESULT = new RedirectInfo(file, true);
        :}
    ;
