import java_cup.runtime.*;
import java.util.*;

terminal NEWLINE, PIPE, SEMI, REDIR, APPEND;
terminal String IDENT;

non terminal Object line;
non terminal Object cmd_list;

non terminal Object command;
non terminal List<CommandExecutor.SimpleCommand> pipeline;
non terminal CommandExecutor.SimpleCommand simple_cmd;

non terminal List<String> args;
non terminal RedirectInfo redir;

start with line;

line ::=
      cmd_list NEWLINE
    | NEWLINE
    ;

cmd_list ::=
      command
    | cmd_list SEMI command
    ;

command ::=
      pipeline:p redir:r
      {:
          CommandExecutor.executePipeline(p, r);
          RESULT = null;
      :}
    ;

pipeline ::=
      simple_cmd:c
      {:
          List<CommandExecutor.SimpleCommand> l = new ArrayList<>();
          l.add(c);
          RESULT = l;
      :}
    | pipeline:p PIPE simple_cmd:c
      {:
          p.add(c);
          RESULT = p;
      :}
    ;

simple_cmd ::=
      IDENT:cmd args:a
      {:
          RESULT = new CommandExecutor.SimpleCommand(cmd, a);
      :}
    ;

args ::=
      {:
          RESULT = new ArrayList<String>();
      :}
    | args:a IDENT:i
      {:
          a.add(i);
          RESULT = a;
      :}
    ;

redir ::=
      {:
          RESULT = null;
      :}
    | REDIR IDENT:file
      {:
          RESULT = new RedirectInfo(file, false);
      :}
    | APPEND IDENT:file
      {:
          RESULT = new RedirectInfo(file, true);
      :}
    ;
